[PREP]
data_dir = "/PATH/TO/DATA/032212"
output_dir = "/PATH/TO/DATA/vak/prep/train"
audio_format = "cbin"
annot_format = "notmat"
labelset = "iabcdefghjk"
train_dur = 50
val_dur = 15
test_dur = 30

[SPECT_PARAMS]
fft_size = 512
step_size = 64
freq_cutoffs = [ 500, 10000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TRAIN]
models = [ "TweetyNet",]
root_results_dir = "/PATH/TO/DATA/vak/train/results"
batch_size = 8
num_epochs = 2
normalize_spectrograms = true
val_step = 50
ckpt_step = 200
patience = 4
csv_path = "/PATH/TO/DATA/prep/train/032312_prep_200209_123939.csv"

[TweetyNet.optimizer]
lr = 0.001
